<?php

return [
    'repos' => [
        'ash-jc-allen' => [
            'find-a-pr',
            'short-url',
            'laravel-exchange-rates',
            'favicon-fetcher',
            'laravel-config-validator',
        ],
        'laravel' => [
            'framework',
            'docs',
            'vapor-core',
            'octane',
        ],
        'laravelio' => [
            'laravel.io',
        ],
        'laravel-filament' => [
            'filament',
        ],
        'spatie' => [
            '.github', '7to5', 'ElasticsearchDSL', 'Laravel-Excel', 'Mailcoach', 'PHP-SQL-Parser', 'activitylog', 'advanced-nova-media-library',
            'analytics-reports', 'analytics-statistics', 'array-functions', 'array-to-xml', 'asset-helper', 'async', 'async-benchmark',
            'attended.io', 'backtrace', 'belgian-cities-geocoded', 'better-types', 'blender', 'blender-content-blocks',
            'blender-css', 'blender-gulp', 'blender-js', 'blender-media', 'blender-model', 'blink', 'box', 'bpost-address-webservice',
            'browsershot', 'calendar-links', 'calendar-months', 'checklist-going-live', 'checklist-server-setup', 'checkout',
            'client-side-validation', 'code-outliner', 'color', 'commonmark-highlighter', 'commonmark-shiki-highlighter',
            'cpu-load-health-check', 'craft-ray', 'crawler', 'critic', 'crypto', 'css-styleguide', 'dashboard-coffee-listener',
            'dashboard.spatie.be', 'dashboard.spatie.be-external-sensors', 'data-transfer-object', 'db-dumper', 'dns', 'dnsrecords.io',
            'docker', 'docs.spatie.be', 'docs.spatie.be-old', 'docsearch-configs', 'dom-component-parser', 'dragula-constrain',
            'dropbox-api', 'drupal-ray', 'dump-die', 'elasticsearch-php', 'elasticsearch-query-builder', 'elasticsearch-search-string-parser',
            'eloquent-sortable', 'email-concealer', 'email-concealer-cli', 'emits-change', 'emoji', 'enum', 'eslint-config-spatie',
            'event-server', 'file-system-watcher', 'first-or-create-racing-condition-demo', 'flare-branding', 'flare-client-php',
            'flare-vite-plugin-sourcemap-uploader', 'flareapp.io-roadmap', 'flysystem-dropbox', 'flysystem-google-cloud-storage',
            'font-awesome-filetypes', 'fork', 'form-backend-validation', 'form-backend-validation-example-app', 'fractalistic',
            'fragment-importer', 'freek.dev', 'front-line-php.com', 'geocoder', 'github-actions-watcher', 'github-readme-section-updater',
            'global-ray', 'google-time-zone', 'googlesearch', 'guidelines.spatie.be', 'guzzle-logger', 'guzzle-rate-limiter-middleware',
            'guzzle-redirect-history-middleware', 'highlightjs-blade', 'homestead-custom', 'html-element', 'http-status-check',
            'ia-writer-template', 'icalendar-generator', 'ignition', 'ignition-app', 'ignition-ui', 'image', 'image-optimizer',
            'integration', 'interactive-slack-notification-channel', 'intertwine', 'invade', 'javascript-styleguide',
            'larabank-aggregates', 'larabank-eventsauce', 'larabank-projectors', 'larabank-traditional', 'laracon-route-discovery-demo',
            'laravel-activitylog', 'laravel-analytics', 'laravel-artisan-dd', 'laravel-artisan-dispatchable', 'laravel-authorize',
            'laravel-auto-discoverer', 'laravel-backup', 'laravel-beyond-crud.com', 'laravel-binary-uuid', 'laravel-blade',
            'laravel-blade-javascript', 'laravel-blade-x', 'laravel-blink', 'laravel-ciphersweet', 'laravel-collection-macros',
            'laravel-comments-app', 'laravel-comments.com', 'laravel-context-demo', 'laravel-cookie-consent', 'laravel-cors',
            'laravel-cronless-schedule', 'laravel-csp', 'laravel-dashboard', 'laravel-dashboard-attendances-tile',
            'laravel-dashboard-belgian-trains-tile', 'laravel-dashboard-calendar-tile', 'laravel-dashboard-coffee-tile',
            'laravel-dashboard-oh-dear-uptime-tile', 'laravel-dashboard-skeleton-tile', 'laravel-dashboard-time-weather-tile',
            'laravel-dashboard-twitter-tile', 'laravel-dashboard-velo-tile', 'laravel-data', 'laravel-database-mail-templates',
            'laravel-db-snapshots', 'laravel-demo-mode', 'laravel-development-dashboard', 'laravel-directory-cleanup',
            'laravel-disable-floc', 'laravel-discord-alerts', 'laravel-disk-monitor', 'laravel-enum', 'laravel-event-projector',
            'laravel-event-projector-demo-app', 'laravel-event-sourcing', 'laravel-eventsauce', 'laravel-example', 'laravel-export',
            'laravel-failed-job-monitor', 'laravel-feed', 'laravel-flash', 'laravel-fractal', 'laravel-github-webhooks',
            'laravel-glide', 'laravel-google-calendar', 'laravel-google-cloud-storage', 'laravel-google-fonts', 'laravel-googletagmanager',
            'laravel-health', 'laravel-honeypot', 'laravel-html', 'laravel-http-logger', 'laravel-ignition', 'laravel-ignition-app',
            'laravel-image-optimizer', 'laravel-interacts-with-payload', 'laravel-json-api-paginate', 'laravel-link-checker',
            'laravel-littlegatekeeper', 'laravel-livewire-wizard', 'laravel-livewire-wizard-demo-app', 'laravel-log-dumper',
            'laravel-login-link', 'laravel-mail-preview', 'laravel-mailable-test', 'laravel-mailcoach-docs-old', 'laravel-mailcoach-editor',
            'laravel-mailcoach-mailgun-feedback', 'laravel-mailcoach-mailgun-setup', 'laravel-mailcoach-markdown-editor',
            'laravel-mailcoach-monaco', 'laravel-mailcoach-postmark-feedback', 'laravel-mailcoach-postmark-setup',
            'laravel-mailcoach-sendgrid-feedback', 'laravel-mailcoach-sendgrid-setup', 'laravel-mailcoach-ses-feedback',
            'laravel-mailcoach-ses-setup', 'laravel-mailcoach-unlayer', 'laravel-markdown', 'laravel-medialibrary',
            'laravel-medialibrary-pro-app', 'laravel-medialibrary-v6-to-v7-filesystem-upgrade', 'laravel-menu', 'laravel-migrate-fresh',
            'laravel-missing-page-redirector', 'laravel-mix-preload', 'laravel-mix-purgecss', 'laravel-model-cleanup',
            'laravel-model-info', 'laravel-model-states', 'laravel-model-status', 'laravel-morph-map-generator', 'laravel-multitenancy',
            'laravel-navigation', 'laravel-newsletter', 'laravel-onboard', 'laravel-options', 'laravel-or-abort', 'laravel-package-tools',
            'laravel-paginateroute', 'laravel-partialcache', 'laravel-permission', 'laravel-personal-data-export', 'laravel-pjax',
            'laravel-prefixed-ids', 'laravel-query-builder', 'laravel-query-builder-security-issue-poc', 'laravel-queue-aware',
            'laravel-queueable-action', 'laravel-queued-db-cleanup', 'laravel-queues-demo-app', 'laravel-random-command',
            'laravel-rate-limited-job-middleware', 'laravel-ray', 'laravel-ray-demo-app', 'laravel-rdap', 'laravel-referer',
            'laravel-relatable', 'laravel-remote', 'laravel-resource-links', 'laravel-responsecache', 'laravel-robots-middleware',
            'laravel-route-attributes', 'laravel-route-discovery', 'laravel-schedule-monitor', 'laravel-schemaless-attributes',
            'laravel-searchable', 'laravel-server-monitor', 'laravel-server-side-rendering', 'laravel-server-side-rendering-examples',
            'laravel-settings', 'laravel-short-schedule', 'laravel-signal-aware-command', 'laravel-site-search', 'laravel-sitemap',
            'laravel-slack-alerts', 'laravel-slack-slash-command', 'laravel-sluggable', 'laravel-sql-commenter', 'laravel-stats',
            'laravel-stripe-webhooks', 'laravel-stubs', 'laravel-support-bubble', 'laravel-tags', 'laravel-tail', 'laravel-tinker-tools',
            'laravel-translatable', 'laravel-translation-loader', 'laravel-twitter-streaming-api', 'laravel-twitter-streaming-api-example-app',
            'laravel-typescript-transformer', 'laravel-uptime-monitor', 'laravel-url-signer', 'laravel-utm-forwarder',
            'laravel-validation-rules', 'laravel-varnish', 'laravel-view-components', 'laravel-view-models', 'laravel-visit',
            'laravel-visit-app', 'laravel-web-tinker', 'laravel-webhook-client', 'laravel-webhook-server', 'laravel-welcome-notification',
            'laravel4-googletagmanager', 'laravelpackage.training', 'last-fm-now-playing', 'macroable', 'mailchimp-boilerplate',
            'mailcoach-packages', 'mailcoach-packer', 'mailcoach-support', 'mailcoach-ui', 'mailcoach-vapor',
            'medialibrary-app', 'medialibrary-demo', 'medialibrary.pro', 'meetup.laravel.com', 'menu', 'mixed-content-scanner',
            'mixed-content-scanner-cli', 'myray.app', 'newsletter-form', 'nova-app-event-projector', 'nova-backup-tool',
            'nova-tags-field', 'nova-tail-tool', 'nova-translatable', 'nova-translatable-testapp', 'npm-install-peers',
            'once', 'one-package-to-rule-them-all', 'opening-hours', 'opening-hours-js', 'or-else', 'ozzie.spatie.be',
            'package-skeleton-laravel', 'package-skeleton-php', 'package-sync', 'packagist-api', 'payment', 'pdf-to-image',
            'pdf-to-text', 'period', 'pest-plugin-snapshots', 'pest-plugin-test-time', 'php-cloneable', 'phpstan-module-boundaries',
            'phpstorm-blade-x', 'phpunit-docker-assertions', 'phpunit-snapshot-assertions', 'phpunit-watcher', 'postcss-purgecss-laravel',
            'psalm-plugin-laravel', 'query-string', 'query-string-js', 'radiorarefish.be', 'rails-ray', 'ray', 'ray-bundle',
            'refactor-complex-conditional', 'regex', 'robots-txt', 'ruby-ray', 'scheduled-tweets-app', 'schema-org', 'scout-extended',
            'scss', 'searchindex', 'security-advisories-health-check', 'seeders', 'selenium-client', 'server-monitor-app',
            'server-side-rendering', 'sheets', 'shiki-php', 'sidecar-shiki', 'simple-excel', 'sitesearch', 'skeleton-js',
            'skeleton-nova-tool', 'skeleton-vue', 'skeleton-wires', 'sketch', 'slack-committer', 'snippets', 'spatie-attachment-uploader',
            'spatie-dom', 'spatie-front.js', 'spatie-price-api', 'spatie.be', 'spoon', 'ssh', 'ssl-certificate', 'ssl-certificate-chain-resolver',
            'statamic-algolia-places', 'statamic-blade-starter-kit', 'statamic-health', 'statamic-mailcoach', 'statamic-responsive-images',
            'string', 'sun', 'symfony-ignition-bundle', 'tailwind-safelist-generator', 'take-then', 'tax-calculator',
            'temporary-directory', 'test-time', 'tinker.app', 'tinker.app-image', 'twitter-labs', 'twitter-oembed', 'twitter-streaming-api',
            'typed', 'typescript-transformer', 'unit-conversions', 'uptime-monitor-app', 'url', 'url-signer', 'uuid-mysql-performance',
            'valuestore', 'velo', 'viewport-utility', 'visit', 'vue-data-component', 'vue-data-component-source', 'vue-expose-inject',
            'vue-filterable-list', 'vue-pjax', 'vue-save-state', 'vue-table-component', 'vue-tabs-component', 'webpack',
            'weight-conversions', 'wires', 'wordpress-ray', 'workshop-laravel-package', 'workshop-unit-conversions', 'x-ray',
            'yaml-front-matter', 'yii-ray',
        ],
        'crwlrsoft' => [
            'crawler',
            'url',
            'query-string',
            'robots-txt',
        ],
        'yieldigit' => [
            'synext',
        ],
        'php-flasher' => [
            'php-flasher',
            'php-flasher.github.io',
            'flasher-js',
        ],
        'symfony' => [
            '.github', 'acl-bundle', 'all-my-sms-notifier', 'amazon-mailer', 'amazon-sns-notifier', 'amazon-sqs-messenger',
            'amqp-messenger', 'amqp-pack', 'apache-pack', 'asset', 'assetic-bundle', 'beanstalkd-messenger', 'binary-utils',
            'browser-kit', 'cache', 'cache-contracts', 'cli', 'clickatell-notifier', 'clock', 'config',
            'console', 'contact-everyone-notifier', 'contracts', 'crowdin-translation-provider', 'css-selector', 'debug',
            'debug-bundle', 'debug-pack', 'demo', 'dependency-injection', 'deprecation-contracts', 'discord-notifier',
            'diversity', 'doctrine-bridge', 'doctrine-messenger', 'dom-crawler', 'dotenv', 'engagespot-notifier', 'error-handler',
            'esendex-notifier', 'event-dispatcher', 'event-dispatcher-contracts', 'expo-notifier', 'expression-language',
            'fake-chat-notifier', 'fake-sms-notifier', 'filesystem', 'finder', 'firebase-notifier', 'flex', 'force-lowest',
            'form', 'forty-six-elks-notifier', 'framework-bundle', 'free-mobile-notifier', 'gateway-api-notifier', 'gitter-notifier',
            'google-chat-notifier', 'google-mailer', 'html-sanitizer', 'http-client', 'http-client-contracts', 'http-foundation',
            'http-kernel', 'icu', 'inflector', 'infobip-mailer', 'infobip-notifier', 'intl', 'intl-data', 'iqsms-notifier',
            'kaz-info-teh-notifier', 'ldap', 'light-sms-notifier', 'linked-in-notifier', 'locale', 'lock', 'loco-translation-provider',
            'lokalise-translation-provider', 'lts', 'mail-pace-mailer', 'mailchimp-mailer', 'mailer', 'mailgun-mailer',
            'mailjet-mailer', 'mailjet-notifier', 'maker-bundle', 'marketing', 'mattermost-notifier', 'mercure', 'mercure-bundle',
            'mercure-notifier', 'message-bird-notifier', 'message-media-notifier', 'messenger', 'microsoft-teams-notifier',
            'mime', 'mobyt-notifier', 'monolog-bridge', 'monolog-bundle', 'nexmo-notifier', 'notifier', 'octopush-notifier',
            'oh-my-smtp-mailer', 'one-signal-notifier', 'options-resolver', 'orange-sms-notifier', 'orm-pack', 'ovh-cloud-notifier',
            'panther', 'password-hasher', 'phpunit-bridge', 'platformsh-pack', 'polyfill', 'polyfill-apcu', 'polyfill-ctype',
            'polyfill-iconv', 'polyfill-intl-grapheme', 'polyfill-intl-icu', 'polyfill-intl-idn', 'polyfill-intl-messageformatter',
            'polyfill-intl-normalizer', 'polyfill-mbstring', 'polyfill-php54', 'polyfill-php55', 'polyfill-php56', 'polyfill-php70',
            'polyfill-php71', 'polyfill-php72', 'polyfill-php73', 'polyfill-php74', 'polyfill-php80', 'polyfill-php81',
            'polyfill-php82', 'polyfill-util', 'polyfill-uuid', 'polyfill-xml', 'postmark-mailer', 'process', 'profiler-pack',
            'propel1-bridge', 'property-access', 'property-info', 'proxy-manager-bridge', 'psr-http-message-bridge', 'psr7-meta',
            'psr7-pack', 'rate-limiter', 'recipes', 'recipes-contrib', 'redis-messenger', 'requirements-checker', 'rocket-chat-notifier',
            'routing', 'runtime', 'security', 'security-acl', 'security-bundle', 'security-core', 'security-csrf', 'security-guard',
            'security-http', 'semaphore', 'sendberry-notifier', 'sendgrid-mailer', 'sendinblue-mailer', 'sendinblue-notifier',
            'serializer', 'serializer-pack', 'service-contracts', 'sinch-notifier', 'skeleton', 'slack-notifier', 'sms-biuras-notifier',
            'sms-factor-notifier', 'sms77-notifier', 'smsapi-notifier', 'smsc-notifier', 'spot-hit-notifier', 'stimulus-bridge',
            'stimulus-testing', 'stopwatch', 'string', 'swiftmailer-bridge', 'swiftmailer-bundle', 'symfony', 'symfony-docs',
            'symfony-hello-world', 'symfony-installer', 'symfony-standard', 'symfony1', 'symfony1-docs', 'telegram-notifier',
            'telnyx-notifier', 'templating', 'test-pack', 'thanks', 'translation', 'translation-contracts', 'turbo-sms-notifier',
            'twig-bridge', 'twig-bundle', 'twig-pack', 'twilio-notifier', 'uid', 'ux', 'ux-autocomplete', 'ux-chartjs',
            'ux-cropperjs', 'ux-dropzone', 'ux-lazy-image', 'ux-live-component', 'ux-notify', 'ux-react', 'ux-swup', 'ux-turbo',
            'ux-turbo-mercure', 'ux-twig-component', 'ux-typed', 'validator', 'var-dumper', 'var-exporter', 'vonage-notifier',
            'web-link', 'web-profiler-bundle', 'web-server-bundle', 'webapp-meta', 'webapp-pack', 'webpack-encore', 'webpack-encore-bundle',
            'website-skeleton', 'workflow', 'yaml', 'yunpian-notifier', 'zendesk-notifier', 'zulip-notifier',
        ],
        'ylsideas' => [
            'cockroachdb-laravel', 'feature-flags', 'subscribable-notifications',
        ],
    ],

    'labels' => [
        'findapr',
        'good first issue',
        'first issue',
        'first pr',
        'help wanted',
    ],

    'reactions' => [
        '+1' => '👍', // \u{1F44D}
        '-1' => '👎', // \u{1F44E}
        'laugh' => '😄', // \u{1F604}
        'hooray' => '🎉', // \u{1F389}
        'confused' => '😕', // \u{1F615}
        'heart' => '❤️', // \u{2764}
        'rocket' => '🚀', // \u{1F680}
        'eyes' => '👀', // \u{1F440}
    ],
];
