name: NPM Dependencies

on:
  workflow_call:
  schedule:
    - cron: '23 8 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  npm:
    name: NPM Dependency Audit
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'
          package-manager-cache: false

      - name: Audit NPM dependencies
        run: npm audit --package-lock-only --include=dev --audit-level=low
