name: TestSuite

on: [pull_request, push]

jobs:
  phpunit:
    runs-on: ubuntu-24.04

    steps:
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 8.4
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          npm ci
          npm run build
      - name: Run Testsuite
        run: php artisan test
